### ISSUE TITLE
Missing HTML Template

### ISSUE THREAD

**Issue by GMarzinotto** [cryptoapi/Python-Django-Flask-Bitcoin-Payments#1]
Hello,

I'm trying to test the API using Flask
However I'm getting confused on how to deploy a payment box on the client side

I see in  def cryptobox_rendering(request):

that it renders a 'cryptobox_template.html'  but I haven't been able to find this html template

Thank you very much for you help!
Kind Regards,
Gabriel M

**Comment by cryptoapi** [comment]
Added Template
